services:
  # api:
  #   build: .
  #   container_name: rolafoody-api
  #   ports:
  #     - 5000:5000
  #   command: "npm start"

  rolamax-mongodb:
    container_name: rolafoody-mongodb
    image: mongo
    restart: always
    command: "mongod --port 27017"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rolamenttrade
      MONGO_INITDB_ROOT_PASSWORD: Rotimi051280
    volumes:
      - ./data:/data/db

  medLink-mongo-express:
    container_name: rolafoody-mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8080:8080
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rolamenttrade
      ME_CONFIG_MONGODB_ADMINPASSWORD: Rotimi051280
      ME_CONFIG_MONGODB_URL: mongodb+srv://rolamenttrade:Rotimi051280@cluster0.g1nw9yr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      ME_CONFIG_BASICAUTH: false
